[cambio]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "creado"
etiqueta[]  = "Creado"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "modificado"
etiqueta[]  = "Modificado"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "moneda1_id"
etiqueta[]  = "Moneda"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "moneda2_id"
etiqueta[]  = "Moneda"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "operacion"
etiqueta[]  = "Operacion"
ayuda[]     = "Por favor Introduzca el tipo de Operación"
error[]     = "El campo no puede ser vacio"

campo[]     = "valor_moneda1"
etiqueta[]  = "Valor"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "valor_moneda2"
etiqueta[]  = "Valor"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"


[clientes]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "adjunto"
etiqueta[]  = "Adjunto"
ayuda[]     = ""
error[]     = ""

campo[]     = "apellido"
etiqueta[]  = "Apellidos"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "creado"
etiqueta[]  = "Creado"
ayuda[]     = ""
error[]     = ""

campo[]     = "direccion"
etiqueta[]  = "Direccion"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "dni"
etiqueta[]  = "DNI"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "modificado"
etiqueta[]  = "Modificado"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombres"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "pais_id"
etiqueta[]  = "Pais"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "tlf"
etiqueta[]  = "Telefono"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "tlf2"
etiqueta[]  = "Telefono Opc"
ayuda[]     = ""
error[]     = ""

campo[]     = "correo"
etiqueta[]  = "Correo"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio o no es válido"


[estados_operaciones]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "creado"
etiqueta[]  = "Creado"
ayuda[]     = ""
error[]     = ""

campo[]     = "descripcion"
etiqueta[]  = "Descripcion"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "modificado"
etiqueta[]  = "Modificado"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = "Por favor Introduzca el nombre del posible estado de la transacciones"
error[]     = "El campo no puede ser vacio"


[monedas]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "abreviacion"
etiqueta[]  = "Abreviacion"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "creado"
etiqueta[]  = "Creado"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "modificado"
etiqueta[]  = "Modificado"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = "Por favor Introduzca el nombre de la Moneda"
error[]     = "El campo no puede ser vacio"


[niveles]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "creado"
etiqueta[]  = "Creado"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "modificado"
etiqueta[]  = "Modificado"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = "Por favor Introduzca el nombre del Nivel de Acceso"
error[]     = "El campo no puede ser vacio"


[paises]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "creado"
etiqueta[]  = "Creado"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "modificado"
etiqueta[]  = "Modificado"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = "Por favor Introduzca el nombre del pais"
error[]     = "El campo no puede ser vacio"


[personal]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "apellido"
etiqueta[]  = "Apellido"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "clave"
etiqueta[]  = "Clave"
ayuda[]     = "La clave debe contener minimo 6 letras una mayuscula y un caracter especial"
error[]     = "El campo no puede ser vacio"

campo[]     = "estado"
etiqueta[]  = "Estado"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "dni"
etiqueta[]  = "DNI"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "login"
etiqueta[]  = "Login"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "nivel_id"
etiqueta[]  = "Nivel de Acceso"
ayuda[]     = "Por favor Introduzca el Nivel de Acceso del Usuario"
error[]     = "El campo no puede ser vacio"

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "sucursal_id"
etiqueta[]  = "Sucursal"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "correo"
etiqueta[]  = "Correo"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "direccion"
etiqueta[]  = "Direccion"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "foto"
etiqueta[]  = "Foto"
ayuda[]     = ""
error[]     = ""

campo[]     = "personal_id"
etiqueta[]  = "Personal_id"
ayuda[]     = ""
error[]     = ""

campo[]     = "tlf_fijo"
etiqueta[]  = "Telefono Fijo"
ayuda[]     = ""
error[]     = ""

campo[]     = "tlf_movil"
etiqueta[]  = "Telefono Movil"
ayuda[]     = ""
error[]     = ""

[privilegios]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "acceso"
etiqueta[]  = "Acceso"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "nivel_id"
etiqueta[]  = "Nivel de Acceso"
ayuda[]     = "Por favor Introduzca el nombre del Nivel de Acceso"
error[]     = "El campo no puede ser vacio"

campo[]     = "pagina"
etiqueta[]  = "Pagina"
ayuda[]     = "Por Favor seleccione la Pagina, el nivel de acceso y el Privilegio"
error[]     = "La lista no puede estar vacia"


[sucursales]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "creado"
etiqueta[]  = "Creado"
ayuda[]     = ""
error[]     = ""

campo[]     = "direccion"
etiqueta[]  = "Direccion"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "modificado"
etiqueta[]  = "Modificado"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = "Por favor Introduzca el nombre de la sucursal"
error[]     = "El campo no puede ser vacio"

campo[]     = "pais_id"
etiqueta[]  = "Pais"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "persona_contacto"
etiqueta[]  = "Persona Contacto"
ayuda[]     = ""
error[]     = ""

campo[]     = "tlf"
etiqueta[]  = "Telefono"
ayuda[]     = ""
error[]     = ""

campo[]     = "tlf2"
etiqueta[]  = "Telefono2 (Opcional)"
ayuda[]     = ""
error[]     = ""


[transacciones]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "cliente_envia_id"
etiqueta[]  = "Cliente Envia"
ayuda[]     = "Por favor seleccione de la ventana emergente el cliente que envia"
error[]     = "El campo no puede ser vacio"

campo[]     = "cliente_recibe_id"
etiqueta[]  = "Cliente Recibe"
ayuda[]     = "Por favor seleccione de la ventana emergente el cliente que ReciBe"
error[]     = "El campo no puede ser vacio"

campo[]     = "creado"
etiqueta[]  = "Creado"
ayuda[]     = ""
error[]     = ""

campo[]     = "estado_id"
etiqueta[]  = "Estado"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "modificado"
etiqueta[]  = "Modificado"
ayuda[]     = ""
error[]     = ""

campo[]     = "moneda_envia_id"
etiqueta[]  = "Moneda Envia"
ayuda[]     = ""
error[]     = ""

campo[]     = "moneda_recibe_id"
etiqueta[]  = "Moneda Recibe"
ayuda[]     = ""
error[]     = ""

campo[]     = "monto_envia"
etiqueta[]  = "Monto Envia"
ayuda[]     = ""
error[]     = "El campo no puede ser vacio"

campo[]     = "monto_recibe"
etiqueta[]  = "Monto Recibe"
ayuda[]     = ""
error[]     = ""

campo[]     = "personal_id"
etiqueta[]  = "Personal"
ayuda[]     = ""
error[]     = ""

campo[]     = "sucursal_envia_id"
etiqueta[]  = "Sucursal Envia"
ayuda[]     = ""
error[]     = ""

campo[]     = "sucursal_recibe_id"
etiqueta[]  = "Sucursal Recibe"
ayuda[]     = ""
error[]     = ""


[usuarios]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "activo"
etiqueta[]  = "Activo"
ayuda[]     = ""
error[]     = ""

campo[]     = "clave"
etiqueta[]  = "Clave"
ayuda[]     = ""
error[]     = ""

campo[]     = "email"
etiqueta[]  = "Email"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "nivel"
etiqueta[]  = "Nivel"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = ""
error[]     = ""

